vrk-kpa/restricteddata

.gitignore, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/tests/test_plugin.py, ckan/templates/production.ini.j2, ruff.toml
- Disable new user registration
- Added .gitignore
=> REKDAT-6: Disable registration

.github/workflows/test.yml, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/tests/test_plugin.py, ckan/ckanext/ckanext-registrydata/test.ini, codecov.yml
- Added test job to CI
- Added codecov.yml
=> REKDAT-6: Added actions for running unit tests and submitting to codecov

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/dcat.py, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/plugin.py, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/tests/test_dcat.py, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/tests/test_plugin.py, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/tests/utils.py, ckan/ckanext/ckanext-registrydata/test.ini
- Mapped all fields currently defined in data model with translations
- Tests for every field
=> REKDAT-18: DCAT-AP profile

cdk/bin/cdk.ts, cdk/cdk.context.json, cdk/lib/common-stack-props.ts, cdk/lib/database-stack-props.ts, cdk/lib/database-stack.ts, cdk/lib/kms-key-stack.ts
Adds database stacks with one instance to each environment.
=> REKDAT-2: Add kms key and database stacks

.github/workflows/main.yml, cdk/bin/cdk.ts, cdk/lib/load-balancer-stack.ts
Creates load balancer and log bucket but doesn't bind it to anything yet. Outputs CI deploy logs also on successes for debugging deploy anomalie.
=> REKDAT-35: Create load balancer in cdk

cdk/bin/cdk.ts, cdk/lib/create-databases-and-users-props.ts, cdk/lib/create-databases-and-users.function.ts, cdk/lib/create-databases-and-users.ts, cdk/lib/database-stack.ts, cdk/lib/kms-key-stack.ts, cdk/lib/lambda-stack-props.ts, cdk/lib/lambda-stack.ts, cdk/package-lock.json, cdk/package.json
- Added `LambdaStack`
- Added `CreateDatabasesAndUsers` lambda
- Export database stack information through properties
=> REKDAT-30: Added lambda stack to create CKAN database and database user

cdk/bin/cdk.ts, cdk/lib/domain-stack-props.ts, cdk/lib/domain-stack.ts, cdk/lib/sub-domain-stack-props.ts, cdk/lib/sub-domain-stack.ts, cdk/test/domain-stack.test.ts
Creates subzones and cross account delegate to bind subzone from dev account to prod account public zone. Binds loadbalancer to subzone domain.
=> REKDAT-32: Add subzones and bind loadbalancer

cdk/bin/cdk.ts, cdk/lib/backup-stack-props.ts, cdk/lib/backup-stack.ts, cdk/lib/database-stack-props.ts, cdk/lib/database-stack.ts
- Added backupstack and configuration for dev/prod
=> REKDAT-34: Added backup stack

assets/src/scss/base.scss, assets/src/scss/ckan/main.scss, assets/src/scss/fonts.scss, assets/src/scss/icons.scss, assets/src/scss/mixins.scss, assets/src/scss/variables.scss, ckan/Dockerfile, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/assets/webassets.yml, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/base.html, ckan/src/ckan/patches/remove-ckan-fontawesome.patch, gulpfile.js
Added base styles as basis for registrydata theme
=> REKDAT-20: Add base styles

assets/src/scss/base.scss, assets/src/scss/ckan/datasets.scss, assets/src/scss/ckan/home.scss, assets/src/scss/ckan/main.scss, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/home/layout1.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/package/search.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/snippets/home_breadcrumb_item.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/snippets/search_form.html
- Combined common styles with front page
- Styled dataset search
=> REKDAT-25: Styled dataset search

assets/src/scss/base.scss, assets/src/scss/ckan/datasets.scss, assets/src/scss/ckan/main.scss, assets/src/scss/ckan/organizations.scss, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/organization/snippets/organization_item.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/organization/snippets/organization_list.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/package/search.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/snippets/search_form.html, ckan/templates/ckan.ini.j2
- Combined some styles with dataset search
- remove padding from primary module content to align with secondary content
- Disable CKAN cache in dev environment
=> REKDAT-27: Styled organization search

assets/src/scss/base.scss, assets/src/scss/ckan/datasets.scss, assets/src/scss/ckan/organizations.scss, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/organization/read.html
- Styled organization page
- Fixed some styles in organization and dataset listing pages
=> REKDAT-28: Styled organization page

assets/src/scss/base.scss, assets/src/scss/ckan/datasets.scss, assets/src/scss/ckan/footer.scss, assets/src/scss/ckan/home.scss, assets/src/scss/ckan/main.scss, assets/src/scss/ckan/organizations.scss, assets/src/scss/ckan/pages.scss, assets/src/scss/variables.scss, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/helpers.py, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/plugin.py, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/home/layout1.html
- Fix caret position in different sized select boxes
- Use variables instead of color tokens directly
- Add basic styling for ckanext-pages pages
=> Utilize variables in SCSS, fix some styles

.github/workflows/test.yml, cdk/lib/create-databases-and-users.function.ts, ckan/setup/app/prerun.py, docker/postgres/Dockerfile
Prerun solr connection test will timeout.
Disables building frontend during tests as fontawesome-pro needs to be replaced by free.
Replaces old postgis container with postgres 15 which is in use in AWS.
Grants priviledges to public schema for ckan user to allow creation of tables.
=> Deployment fixes

cdk/lib/create-databases-and-users.function.ts
Schema permissions need to be given in the correct database.
=> Grant public schema permissions in correct database

.github/workflows/main.yml, .github/workflows/test.yml, assets/src/scss/variables.scss
Caches global dependencies and node_modules separately and skips install if there is a cache available
=> Cache node_modules to reduce fontawesome installs

cdk/lib/create-databases-and-users.ts
No need to exclude separately in database secrets
=> Database secret has sensible default

assets/src/scss/ckan/home.scss, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/i18n/ckanext-registrydata.pot, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/i18n/fi/LC_MESSAGES/ckanext-registrydata.po, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/home/layout1.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/snippets/search_result_text.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/translations.py
- Better category grid badge positioning
- Use months, not minutes in news publish date
- Fix search result text translations
=> Small fixes

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/i18n/ckanext-registrydata.pot, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/i18n/fi/LC_MESSAGES/ckanext-registrydata.po, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/home/layout1.html
- Added aria-labels for home page links with no clear label as content
=> Home aria-labels

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/plugin.py
- Add multilingual keyword indexing for datasets
- Customize dataset search facets
=> REKDAT-43: Added multilingual keyword facet handling

.github/workflows/main.yml, .github/workflows/prod.yml, cdk/bin/cdk.ts
Adds remaining productions stacks and production deployment workflow
=> Add production deployment

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/plugin.py
- Inherit missing facet methods
=> REKDAT-43: Fix organization page facet error

assets/src/scss/variables.scss
Does not affect anything but reference correct code.
=> Fix variable hex code to correct one

cdk/lib/load-balancer-stack.ts
Fixes indentation of the loadbalancer stack file and add redirect from http to https to it.
=> REKDAT-47: redirect http to https

.github/dependabot.yml
- Added dependabot configuration
=> REKDAT-53: Add dependabot configuration

.github/workflows/lint.yml, ckan/Dockerfile, ckan/src/ckan/patches/fix_user_reset_password.patch
Fixed in ckan in https://github.com/ckan/ckan/pull/7871
=> REKDAT-40: Fix password reset with ckan core patch

cdk/bin/cdk.ts, cdk/lib/ckan-stack-props.ts, cdk/lib/ckan-stack.ts
- Added cron task definition to `CkanStackProps`
- Configured cron task for dev and prod
- Added CKAN cron service definition to `CkanStack`
=> REKDAT-41: Add CKAN cron container to CDK CKAN stack

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/package/resource_read.html
- Added conditionality to `resource_views` block
=> REKDAT-62: Only show resource preview section if previews exist

assets/src/scss/ckan/common.scss
- Added bottom padding to match layout
=> Add bottom padding to sidebar and main content view

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/schemas/dataset.json
- Fix validators for mandatory resource fields
=> REKDAT-70: Add validation for mandatory resource fields

cdk/lib/shield-stack.ts
Add missing web acl association.
=> REKDAT-17: Add web acl association

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/plugin.py, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/header.html, ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates_pages/ckanext_pages/base_form.html
- Added submenu_order to pages schema and form
- Added helper to query submenu_order items
- Add submenu_order items to header menu, make a dropdown if needed
=> REKDAT-88: Implement ckanext-pages support for header menu

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/action.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
- Add users automatically to all groups as members to allow adding datasets
=> REKDAT-107: Add users automatically as group members

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/ckanext-restricteddata.pot, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/package/snippets/package_form.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/translations.py
- Update dataset license disclaimer text
=> REKDAT-112: Modify dataset license disclaimer

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/fi/LC_MESSAGES/ckanext-restricteddata.po
- Updated translations for ckanext-restricteddata
=> REKDAT-108: Update translations

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/dataset.json
- Remove license field
- Move group title to next item
=> REKDAT-111: Remove license from dataset fields

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
- Also remove license from dataset search facets
=> REKDAT-111: Remove license from dataset facets

.github/workflows/restart_dev_containers.yml, cdk/lib/ckan-stack.ts
Adds service names to containers so that they don't change, should not have a large effect.
=> Add restart dev containers workflow

cdk/package-lock.json, cdk/package.json
Delegate role lambda is generated by cdk and its runtime is upgraded with the newer cdk.
=> Upgrade cdk

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/organization/read.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/user/read.html
=> REKDAT-144 & REKDAT-145: move content action to page primary action in user read and organization read

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/user/dashboard.html
=> REKDAT-136: Remove groups link from dashboard

cdk/test/domain-stack.test.ts
Increase test coverage to appease codecov
=> Add a CDK DomainStack test for cross delegate role

cdk/bin/cdk.ts, cdk/lib/shield-parameter-stack.ts, cdk/lib/shield-stack-props.ts, cdk/lib/shield-stack.ts, cdk/package-lock.json, cdk/package.json
- Added ShieldParameterStack to create parameters required by ShieldStack
- Ported improvements to ShieldStack from Opendata
=> REKDAT-132: Create WAF parameters in a separate stack

cdk/lib/ckan-stack.ts
Matomo plugins come from its own env variable.
=> Add ckan_plugins_matomo env variable

ckan/ckanext/ckanext-restricteddata/.tx/config, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/en_GB/LC_MESSAGES/ckanext-restricteddata.po, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/fi/LC_MESSAGES/ckanext-restricteddata.po, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/sv/LC_MESSAGES/ckanext-restricteddata.po
Updates translations and updates the tx config to refer hashed slug for github integration.
=> REKDAT-148: Update translations

.github/workflows/main.yml, .github/workflows/prod.yml, .github/workflows/test.yml
assets already use root package-lock.json, use cdk one for cdk node_modules.
=> Use cdk package-lock.json for hashing function when caching cdk node_modules

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/page.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/snippets/alert.html
- Flash message styles broke when service messages were implemented
- Fix styles by using the same alert component
=> Fix flash message styles that broke during service message implementation

.github/workflows/test.yml, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/ckanext-restricteddata.pot, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/fi/LC_MESSAGES/ckanext-restricteddata.po, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/sv/LC_MESSAGES/ckanext-restricteddata.po, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/translations.py, robot/Dockerfile
Built on #245 
- Add missing translations
=> REKDAT-149: missing translations

.github/workflows/test.yml, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/ckanext-restricteddata.pot, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/fi/LC_MESSAGES/ckanext-restricteddata.po, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/sv/LC_MESSAGES/ckanext-restricteddata.po, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/translations.py, robot/Dockerfile
- string in `translations.py` did not match the one in `dataset.json`
- Also put full robot test results into a CI artifact
=> REKDAT-159: Fix translation string in dataset visibility input

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/helpers.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/ckanext-restricteddata.pot, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/dataset.json, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/macros/form/input_block.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/scheming/form_snippets/multiple_checkbox.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/scheming/form_snippets/radio.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/translations.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/validators.py
Adds highvalue categories to datasets.
Makes multiple checkbox template data independent, it used to compare to group data if they are selected or not.
=> REKDAT-150: Add highvalue categories to datasets

.github/workflows/test.yml, .gitignore, ckan/UNIT_TESTING.md
The same change as in https://github.com/vrk-kpa/opendata/pull/2338
=> docker-compose v1 is deprecated and removed

.github/workflows/test.yml, assets/src/scss/alert.scss, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/scheming/snippets/errors.html, ckan/templates/ckan.ini.j2, docker/nginx/templates/server.conf.template
- Recent alert component layout rework broke form validation error list layout, this fixes it to Suomi.fi style
=> REKDAT-167: Fix form validation errors layout

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/converters.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/dataset.json, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/scheming/display_snippets/boolean.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/scheming/package/snippets/additional_info.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/snippets/facet_list.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/snippets/search_form.html, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
Removes highvalue categories if highvalue is false.
Hides rows with empty values from additional details.
Changes boolean radio buttons to be actually boolean in schema.
Adds highvalue categories to facet filters.
Translated highvalue categories in facet filters and pills.
=> REKDAT-151: Fix things missing from UI

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/ckanext-restricteddata.pot, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/organization.json, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/translations.py
Adds vat number to organization schema and extracts messages.
=> REKDAT-184: Add vat number to organization schema

ckan/Dockerfile, docker/docker-compose.build.yml, docker/docker-compose.yml, docker/solr/Dockerfile
Mixed casing in FROM .. AS .. has been giving warnings for awhile, also version in docker compose has been deprecated months ago.
=> Fix warnings

cdk/bin/cdk.ts
Increases vCPU in dev and vCPU, mem and running containers in prod.
=> REKDAT-100: Add extra capacity

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/helpers.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/home/layout1.html
- Remove `get_homepage_news` helper
- Remove news element from homepage layout
=> REKDAT-195: Remove news component

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/action.py
- Added side_effect_free decorator to overridden chained actions that do not change the application state
=> REKDAT-254: Add side_effect_free decorators to read only chained actions

.github/workflows/test.yml, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/validators.py, robot/tests/login.robot
- Add check for github ref in test.yml XRay upload step
=> REKDAT-252: Only upload e2e test results to XRay from main branch

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/action.py, ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
- Created user names were not munged, causing issues with some names
=> REKDAT-309: Fix user name munging in PAHA user creation

.github/workflows/restart_dev_containers.yml, .github/workflows/restart_prod_containers.yml, cdk/lib/nginx-stack.ts
Gives a name to nginx service to allow restart from workflow, will replace the current service during deploy.
=> Allow restart of nginx container from restart workflow

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
- Add IFacets implementations for `group_facets` and `organization_facets` to support similar facets for all dataset views
=> REKDAT-225: add missing IFacets implementations

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
- Add organization to facets
- Remove organization facet from organization facets
=> REKDAT-225: Add organization to group facet filters

ckan/Dockerfile, robot/tests/site_information.robot
- Previous PR only updated dependencies due to the version being installed separately
- Also update robot test to verify version
=> REKDAT-393: Also update CKAN version in dockerfile and tests

.github/dependabot.yml, .github/workflows/changes.yml, .github/workflows/dependabot-validate.yml, .github/workflows/test.yml
Adds dependabot validation workflow.
Adds robot directory to dependabot.
Runs robot tests if there is an change in robot directory.
=> Update robot with dependabot

cloudformation/ecr-scanning-stack.yml
=> REKDAT-556: Add registry scanning template to version control

.github/workflows/prod.yml, .github/workflows/test.yml, cdk/lib/load-balancer-stack.ts, cloudformation/ecr-repository-stack.yml
Ports retagging prod images, lifecycle policies for ecr and loadbalancer. And disables xray reports.
=> Port CI features from avoindata
