.gitignore
ckan/Dockerfile
ckan/UNIT_TESTING.md
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/tests/test_plugin.py
ckan/scripts/init_ckan.sh

- Added instructions for running unit tests locally
- Added gitignore for local unit testing files
- Added `pytest-ckan` to development CKAN image
- Added initializing test database to `init_ckan.sh`
- Fixed a failing unit test (missed cleaning search index)

REKDAT-29: Local unit testing

---

cloudformation/github-actions-stack.yml

GHA requires permission to modify cloudformation and assume cdk role for deployments.

Add required permission for gha deployment

---

cdk/bin/cdk.ts
cdk/lib/certificate-stack-props.ts
cdk/lib/certificate-stack.ts
cdk/lib/domain-stack.ts
cdk/lib/sub-domain-stack.ts

In prod certificates are create using the root public zone, in dev sub public zone is used instead.

REKDAT-33: Add certificate stacks for dev and prod

---

cdk/bin/cdk.ts
cdk/lib/common-stack-props.ts
cdk/lib/ecs-cluster-stack-props.ts
cdk/lib/ecs-cluster-stack.ts
cdk/lib/ecs-stack-props.ts
cdk/lib/ecs-task-definition-props.ts
cdk/lib/env-props.ts
cdk/lib/lambda-stack.ts
cdk/lib/nginx-stack-props.ts
cdk/lib/nginx-stack.ts
cdk/lib/sub-domain-stack-props.ts
cdk/lib/sub-domain-stack.ts
cdk/package-lock.json
cdk/package.json

Various configurations to get nginx container running, still referencing old domain as the new domain hasn't been registered. Configuring A record to loadbalancer is moved to nginx stack to avoid cyclic reference.

REKDAT-31: add ecs cluster and nginx container

---

cdk/bin/cdk.ts
cdk/lib/ecs-stack-props.ts
cdk/lib/efs-stack-props.ts
cdk/lib/filesystem-stack.ts
cdk/lib/nginx-stack-props.ts
cdk/lib/solr-stack.ts
docker/solr/Dockerfile

Adds solr and efs stacks, efs volume is required by solr as the volume is essential to store long term data. Moves some of the properties around for not having to copy paste not needed properties to all stacks.

REKDAT-31: Add solr stack

---

gulpfile.js
package-lock.json
package.json

Instead of bundling all the built sass into a single css file we took... something... and renamed it to registrydata.css. Sometimes it seemed to actually bundle everything into one but other times you'd only get the last file

REKDAT-19: Fix registrydata.css

---

cdk/lib/domain-stack.ts
cdk/lib/sub-domain-stack.ts

Adds new domains to prod domainstack and dev subdomainstack. 
Stacks cannot reference each other, so actual domains need to be more or less hardcoded.

Add new domains to domain stacks

---

cdk/bin/cdk.ts

Might require destroying current stacks due to references but we will see once this is deployed.

Move infrastructure to use new domain

---

cdk/lib/certificate-stack.ts
cdk/lib/domain-stack.ts
cdk/lib/sub-domain-stack.ts
cdk/test/domain-stack.test.ts

Subdomains and certificates are disabled as the domain needs to be registered first on a third party.

REKDAT-48: Replace rekisteridata.fi with suojattudata.suomi.fi

---

ckan/templates/ckan.ini.j2

- Set `beaker.session.cookie_expires = True` in non-dev environments

REKDAT-60: Set session cookies to expire with browser session

---

cdk/bin/cdk.ts
cdk/lib/ckan-stack.ts
cdk/lib/filesystem-stack.ts

.init-done locking requires permanent volume which is shared between ckan service and cron containers.

Add EFS volume to ckan container

---

docker/nginx/templates/site.conf.template

Based of on @bzar findings, use correct cookie in cache bybass in nginx cache.

REKDAT-65: auth cookie has different name in ckan 2.10

---

assets/src/scss/ckan/common.scss
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/package/read.html
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/package/read_base.html

- Make dataset category/activities pages have navigation and layout like the main page
- Tune category grid to match design

REKDAT-61: Fix dataset categories and activity page layouts

---

.github/workflows/main.yml
assets/src/scss/variables.scss

Changes to assets didn't commit new image to .env-template even though the image was pushed.

REKDAT-46: fix tagging images when assets change

---

cdk/lib/ckan-stack.ts
ckan/templates/ckan.ini.j2
docker/.env.ckan.local

cookie based session require this, might be true also when they are stored in database.

REKDAT-65: Add beaker.validate_key for trying to solve session issues

---

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/schemas/dataset.json
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/scheming/macros/form.html

- Check description required languages
- Check repeating email field emptiness before parsing structure
- Handle corner case in repeating text field where no input is rendered

REKDAT-69: Fix dataset mandatory field validation

---

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/scheming/form_snippets/fluent_markdown_editor.html
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/scheming/form_snippets/fluent_tags_with_autocomplete.html
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/scheming/snippets/errors.html

- Fix `fluent_markdown_editor.html` and `fluent_tags_with_autocomplete` to work with `required_languages` validator
- Override scheming `errors.html` to show all errors instead of just the first one

REKDAT-69: Fix dataset validation error reporting

---

ckan/Dockerfile
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/templates/macros/form/input_multiple.html
ckan/src/ckan/patches/remove_extra_head.patch

#151 missed one form parameter and CKAN 2.10.3 introduced extra <<<HEAD in templates, this removes them.

Fix server error in edit dataset form and remove extra <<<HEAD from template

---

ckan/templates/ckan.ini.j2

CKAN for some reason generates a new cookie every now and then and the entry in database doesn't match it anymore and therefore user is logged out. This uses the now default ckan session type which seems to resolve the issue. The cookie has the required information encrypted in it and database should not be needed anymore even when scaling horizontally.

REKDAT-65: Use cookie based sessions to resolve logout issues

---

ckan/ckanext/ckanext-registrydata/ckanext/registrydata/dcat.py
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/doc/dcat-ap/restricteddata_dcat-ap_shacl.ttl
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/tests/test_dcat.py
ckan/ckanext/ckanext-registrydata/ckanext/registrydata/tests/utils.py

- Add empty catalog description if it is missing
- Add catalog publisher information
- Loosen DCAT-AP 3.0.0 SHACL to allow literals by disabling some class and node type checks. This is necessary due to SEMICeu/DCAT-AP#266
- Describe `vcard:Kind` as a shape to correctly validate organization information

REKDAT-95: Fix issues in DCAT-AP 3.0.0 SHACL validation

---

cdk/bin/cdk.ts

Now that the new vault doesn't exist, it needs to be created.

REKDAT-93: Create new backup vault

---

cdk/lib/shield-stack.ts

The same fix as in https://github.com/vrk-kpa/opendata/pull/2185

Fix excluded rules in shield stack

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/dcat.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/doc/dcat-ap/restricteddata_dcat-ap_shacl.ttl
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/dataset.json
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_dcat.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/translations.py

- Make update frequency a select instead of a translated list of strings
- Update DCAT-AP profile to produce references to http://publications.europa.eu/resource/authority/frequency/ vocabulary
- Update tests
- Add translate strings

REKDAT-94: Change update frequency to a controlled vocabulary

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/action.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py

- Override `member_roles_list` to hide `member` user capacity
- Used by member creation UIs

REKDAT-116: Hide `member` user capacity in API/UIs

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/cli/cli.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/cli/migrate.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/cli/migrations.py

- Ported migrate.py from api-catalog
- Added migration for mapping update frequency to new limited selection
- Added CLI tool for applying migrations

REKDAT-131: Added migration tool and 1.4.1->1.5.0 content migration

---

cdk/bin/cdk.ts
cdk/lib/database-stack-props.ts
cdk/lib/efs-stack-props.ts
cdk/lib/shield-stack.ts

- Set termination protection for stacks: 
- DatabaseStackDev
- DatabaseStackProd
- FileSystemStackDev
- FileSystemStackProd
- Remove unnecessary reference to `jasmine`

REKDAT-73: Add termination protection to DB/FS stacks

---

.github/workflows/restart_prod_containers.yml
cloudformation/github-actions-stack.yml

Add similar workflow as restart dev containers and adds missing permission to cloudformation templates.

Restart prod containers workflow

---

.github/workflows/test.yml

https://github.com/marketplace/actions/codecov#breaking-changes
this adds the required token to codecov action.

codecov token is mandatory in the v4 action

---

assets/src/scss/ckan/organizations.scss
gulpfile.js

Adds missing border to organization list items:
Changes sass build to build only main.scss file as it includes other files. Before the resulting css had all the rules twice, this change removes duplicates. Other alternative would be to remove main.scss file all together.

REKDAT-146: Add missing border to organization list

---

assets/src/scss/input.scss
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/macros/form/select.html

REKDAT-147: add missing arrow to select components

---

cdk/lib/lambdas/create-databases-and-users.ts
cdk/lib/lambdas/send-to-zulip.ts

The default runtime in cdk NodejsFunctions was reverted to nodejs 16 in cdk version 2.93.0 and since we updated our cdk from 2.92.0 to the latest, nodejs runtimes were downgraded to version 16. This defines runtime to nodejs 20 explicitly.

REKDAT-135: Use nodejs 20 runtime in lambda functions

---

.github/dependabot.yml

pip requirements are under `ckan` directory and npm dependencies are no longer under `assets`

Update dependabot.yml to refer current directories

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/helpers.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/auth.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/group/snippets/group_item.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/group/snippets/group_list.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/package/group_list.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_helpers.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py

- Added helper for fetching groups the user can modify that the provided package is not a member of if the user can also modify the package
- Update group list templates to use the new helper
- Remove delete button from group list items if the user doesn't have permission to update the related package
- Remove showing 0 group members if the count is not provided
- Override member_create and member_delete auth functions to disallow adding/removing package from a group if the user doesn't have authorization to update both

REKDAT-137: Limit dataset group assignment to users who can update both

---

cdk/bin/cdk.ts
cdk/lib/backup-stack-props.ts
cdk/lib/common-stack-props.ts
cdk/lib/database-stack-props.ts
cdk/lib/ecs-cluster-stack.ts
cdk/lib/efs-stack-props.ts
cdk/lib/env-stack-props.ts
cdk/lib/kms-key-stack.ts
cdk/lib/lambda-stack-props.ts
cdk/lib/lambda-stack.ts
cdk/lib/lambdas/create-databases-and-users-props.ts
cdk/lib/lambdas/send-to-zulip-props.ts
cdk/lib/load-balancer-stack.ts
cdk/lib/monitoring-stack-props.ts
cdk/lib/network-stack-props.ts
cdk/lib/shield-stack-props.ts

Refactors CommonStackProps to smaller interfaces.
```mermaid
---
title: StackProps
---
classDiagram
StackProps <|-- EnvStackProps
EnvStackProps <|-- NetworkStackProps
NetworkStackProps <|-- CommonStackProps 
class StackProps{
object env
}
class EnvStackProps{
string environment
}
class NetworkStackProps{
ec2.IVpc vpc
}
class CommonStackProps{
EnvProps envProps
}
```

Refactor CommonStackProps to EnvStackProps and NetworkStackProps

---

cdk/lib/ckan-stack.ts

Secrets aren't named without preceding slash character.

REKDAT-68: Fix typo in secret name

---

ckan/scripts/init_ckan.sh

Alembic migrations do not create the initial state of database, so the old init command needs to be run.

REKDAT-68: init matomo tables

---

assets/src/scss/alert.scss
assets/src/scss/ckan/main.scss
assets/src/scss/variables.scss
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/ckanext-restricteddata.pot
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/admin/config.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/page.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/snippets/alert.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/snippets/global_messages.html
ckan/templates/ckan.ini.j2

- Added multilingual info messages and service alerts to ckan config schema
- Added text fields to modify the messages from ckan-admin/config
- Added alert-snippet to create dismissable alerts in suomi.fi style
- Added global_messages-snippet to show info messages and service alerts in base layout

REKDAT-91: Add admin-configurable global info messages and service alerts

---

cdk/lib/nginx-stack.ts

Adds matomo domains to allowed script sources.

REKDAT-68: Add matomo to csp headers

---

gulpfile.js

REKDAT-154: gulp v5 requires encoding false when dealing with binary files

---

cdk/lib/solr-stack.ts
docker/docker-compose.yml

The same fix as in https://github.com/vrk-kpa/opendata/pull/2225 and https://github.com/vrk-kpa/opendata/pull/2227, the solr index should be on efs disk mount instead on the container.

REKDAT-157: Fix solr fs mounts

---

.github/workflows/test.yml
cdk/lib/ckan-stack.ts
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/assets/css/restricteddata.css
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
ckan/ckanext/ckanext-restricteddata/setup.cfg
ckan/ckanext/ckanext-restricteddata/test.ini
ckan/templates/ckan.ini.j2
docker/.env.ckan.local

Support for creating users and logging them in using PAHA JWT tokens
- Added configuration for PAHA's JWT key and algorithm. Tests and development environment use symmetric HS256 encryption with a dummy key for simplicity, while AWS environments use RS256 with a separately provided decode key
- `RestrictedDataPahaAuthenticationPlugin` uses a defensive process to determine if the provided bearer token is from PAHA by validating the cryptographic signature. If the identification fails at any point the authentication flow falls back to regular CKAN auth. If the token is valid, the user is identified based on e-mail address and created if it does not exist.
- Added tests for both user creation and logging in with an existing user

REKDAT-127: Add preliminary support for PAHA authentication

---

robot/restricteddata.robot

Robot tests were flaky due to unreliable login
- Added URL check after logging in so the test correctly waits before moving on

Add URL checks to robot test logins

---

.github/workflows/test.yml
ckan/README.md

While running ckan alpine container, codecov@v4 requires gpg and gpg-agent. Additionally v4 doesn't identify alpine correctly.

REKDAT-163: fix codecov upload

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/helpers.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/dataset.json
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/scheming/display_snippets/tag_list.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py

Indexes highvalue categories to vocab index, so that schema doesn't need to be changed. Modifies facet presentation for highvalue categories they don't need to be added as actual vocabularies. Moves the definition of hvd categories to helper to have a single list for them and not define them in multiple places.
Translations are marked as todo on purpose as categories (as in groups) aren't translated either, they need to be solved properly.
Fixes facet label of groups as it said datasets for some reason.

REKDAT-151: Add highvalue categories to UI

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/helpers.py
robot/restricteddata.robot
robot/tests/pages.robot
ruff.toml

- Override ckanext-pages nav build function as it does not support multilingual titles
- Fix deprecated ruff setting
- Added tests for creating header/footer pages items (no unit test due to cross-extension behavior)

REKDAT-162: Fix footer link translations

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/doc/dcat-ap/README.md
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/doc/dcat-ap/index.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/doc/dcat-ap/model.yml
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/doc/dcat-ap/template.html.j2
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/doc/dcat-ap/template.md.j2

- Remove unused properties
- Add required HVD properties
- `dcatap:hvdCategory` is `0..*` cardinality even though [the spec](https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/#Dataset) requires `1..*` since only some of our datasets are HVD
- `dcatap:applicableLegislation` added since a specific value in it is required by the spec, but at `0..*` cardinality for the same reason as above

REKDAT-160: Update DCAT-AP ns page

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/helpers.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/group/read_base.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/group/snippets/group_item.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/group/snippets/info.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/package/group_list.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/package/snippets/categories.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_helpers.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/utils.py
ckan/ckanext/ckanext-restricteddata/test.ini

- Add helpers for translating group titles or group objects
- Translate group titles in search facets
- Translate group titles and descriptions in group lists
- Translate group titles and descriptions in group view
- Translate category titles and descriptions in dataset categories

REKDAT-166: Translate category names and descriptions

---

ckan/scripts/init_ckan.sh

Default categories can still be created from command line, but its not automatic due to the maintaining them.

REKDAT-190: Disable creating default categories

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/auth.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py

Limits create_api_token action to sysadmins only.

REKDAT-175: Limit create api tokens to sysadmins

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/action.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/auth.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py

Built on top of #271 due to the sysadmin only auth function.
Limits user list to sysadmins and modified user_autocomplete to return empty list if auth fails.

REKDAT-170: Limit user list to sysadmins

---

cdk/lib/ckan-stack.ts

- `restricteddata_paha_authentication` plugin was only enabled in local environments, causing errors in cronjobs. Enable it also in CDK deployed environments

Enable PAHA authentication plugin in CDK deployed environments

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/scheming/organization/about.html

Hides vat number field from organization about page.

REKDAT-184: Do not show organization fields that do not have display snippet

---

assets/src/scss/ckan/header.scss
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/i18n/ckanext-restricteddata.pot
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/header.html
ckan/ckanext/ckanext-restricteddata/test.ini

`/dashboard` is under activity blueprint which is some what weird, but there it is anyway.

REKDAT-174: Reconfigure profile link route to dashboard

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/auth.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py

- modify `member_create` and `member_delete` auth functions to defer to `sysadmin_only` if modifying users belonging to a group
- add a test for modifying organization members with both an organization admin and a sysadmin

REKDAT-179: sysadmin only member management

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/header.html

- Set login button url to point to PAHA if the current environment is not a debug environment

REKDAT-173: Login button navigates to PAHA login in non-development environments

---

.github/workflows/scan.yml
cloudformation/github-actions-stack.yml
docker/sast-scanner-meta/Dockerfile
docker/sast-scanner-meta/entrypoint.sh

Adds new workflow to run semgrep and dependency check for pull requests. Probably no need to run these periodically because we dependabot and various github tools to warn us about vulnerable dependencies when the issues arise.

REKDAT-164:  Add workflows for security scans

---

.github/workflows/scan.yml

Security scans need to run on push to main, otherwise they are never run on main branch.

REKDAT-164: Run security scans on push to main

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/user/dashboard.html
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py

- Limit `user_update` actions to sysadmins
- Show "Profile settings" button only if user is permitted to update users
- Added a test for a normal user trying to open their user profile edit page or modifyign their profile over API

REKDAT-172: Limit user profile to sysadmins

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/templates/error_document_template.html

- Override `error_document_template.html` and remove all but error content

REKDAT-169: Remove unnecessary text from error page

---

ckan/ckan-requirements.in
ckan/ckan-requirements.txt

Editable installs required installation via github, ckan is now installed separately so dependencies can be parsed from pypi, might fix dependabot version checks.

Install ckan via pypi, no need to install via github anymore

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py

- disable request_reset and user_reset to disable requesting and performing resets for users
- added a test for requesting resets. performing is not possible because requests cannot be made

REKDAT-253: Disable user reset views for anonymous/normal users

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/action.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/views.py

- Use finnish organization title for sv/en titles if they are empty
- Support multiple organizations with the same title in name generation
- Support different validation error types in paha authorize endpoint
- Amend test for organization title fallback language

REKDAT-309: Add fallback language for PAHA auth created organizations

---

cdk/bin/cdk.ts
cdk/lib/nginx-stack-props.ts
cdk/lib/nginx-stack.ts
cdk/lib/restricteddata-parameter-stack.ts
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/action.py
docker/.env.template
docker/docker-compose.yml
docker/nginx/templates/server.conf.template

- Add realip/allow/deny directives to nginx conf for /paha paths
- Add docker compatible default values for trusted proxy and authentication source address
- Implement CDK support for setting values for trusted proxy and authentication source address
- Fix /paha/authorize response on invalid or missing token

REKDAT-361: Added IP restriction support for paha endpoints

---

.github/dependabot.yml

CDK dependencies weren't automatically updating

Add cdk to dependabot configuration

---

docker/sast-scanner-meta/entrypoint.sh

Semgrep recommends using CI command instead of scan on CI environments.

Use ci cli command in semgrep

---

docker/nginx/Dockerfile
docker/nginx/docker-entrypoint.d/100-install-jinja2-templates.sh
docker/nginx/docker-entrypoint.d/17-install-jinja2-templates.sh

- Jinja2 template rendering happened after nginx template instantiation in priority
- Set priority to 17 so it happens before 20
- Handle some quirks in how entrypoint.d works in the script

REKDAT-361: Fix nginx template generation priority issue

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/dataset.json
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/validators.py
robot/restricteddata.robot
robot/tests/dataset.robot
robot/tests/distribution.robot

- Added validator `populate_required_languages_from_field_if_missing`
- Set validator to distribution `name_translated` field
- Set `required_languages` to distribution `name_translated` field
- Update tests

REKDAT-229: Get default translations for distribution name from url field

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/logic/action.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/dataset.json
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/group.json
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/schemas/organization.json
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/factories.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_dcat.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/utils.py

- Remove swedish translation requirement from data models
- Remove fallback language feature from PAHA auth organization creation
- Fix tests

REKDAT-395: Make swedish optional

---

docker/nginx/Dockerfile

- No need to update package cache when building a new docker image, no other packages will be installed.

Disable package cache when building nginx image

---

ckan/ckan-requirements.in
ckan/ckan-requirements.txt

- Change CKAN version to 2.10.6 in ckan-requirements.in
- Remove gevent requirement in ckan-requirements.in (conflicts with CKAN requirements)
- Regenerate ckan-requirements.txt

REKDAT-393: Upgrade CKAN to 2.10.6

---

ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/model.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/tests/test_plugin.py
ckan/ckanext/ckanext-restricteddata/ckanext/restricteddata/views.py

- Removed `IAuthenticator` implementation in `RestrictedDataPahaAuthenticationPlugin`
- Added `paha.authorized` endpoint for logging in with an authentication token as a GET parameter
- Invalidate token after it is used to successfully log in

REKDAT-465: paha authorized endpoint

---

docker/nginx/jinja2-templates/server.conf.j2

- Previously the nginx configuration blocked all /paha paths from untrusted sources, but the new authorization flow requires clients access /paha/authorized. Now blocking only /paha/authorize is required

Only IP-restrict /paha/authorize path to allow clients to /paha/authorized

---

.github/workflows/main.yml
robot/tests/category.robot
robot/tests/producer.robot

CKAN version test fails as test has been updated but the new container has not been pushed due to flaky test in master.
Adds provenance configuration as in https://github.com/vrk-kpa/opendata/pull/2714

Try to wait for document load before testing that page has changed

---

ckan/Dockerfile

Upgrades alpine to fix some security hub warnings, updates python to latest 3.10 version. Python 3.12 requires updated ckan or at least its dependancies.
Moves base image version out of the variable as dependabot seems to disregard it in variable.

Upgrade python and alpine
